### ISSUE TITLE
Finish documentation

### ISSUE THREAD

**Issue by falkirks** [falkirks/folder-test#4]
* Explain that promises are unwrapped
* A practical example
* yarn add package

**Comment by braxtonhall** [comment]
a "yarn add" line as well would be nice

**Comment by braxtonhall** [comment]
Also, this
https://github.com/falkirks/folder-test/blob/0fd9ce29d5b9dfa532e8d94084ce7684df812c37/src/testFolder.ts#L10
isn't reflected in the actual README lol

**Comment by shizuko-akamoto** [comment]
> Also, this
> https://github.com/falkirks/folder-test/blob/0fd9ce29d5b9dfa532e8d94084ce7684df812c37/src/testFolder.ts#L10
> 
> 
> isn't reflected in the actual README lol

updated in readme API!
